### ISSUE TITLE
请问终端启动浏览器里自定义文件是什么意思？

### ISSUE THREAD

**Issue by jiancheng87** [lktlktlkt/pick-ticket-damai#1]

**Comment by lktlktlkt** [comment]
应该是文件夹，用来存储调式浏览器配置等。使用user-data-dir，不会影响原本使用的浏览器。下一次开启调式浏览器可以一直使用这个文件夹。

**Comment by jiancheng87** [comment]
启动终端后，run了run.py脚本跑不起来，还需要设置其他东西吗？

**Comment by jiancheng87** [comment]
Traceback (most recent call last):
  File "C:\Users\anji\Desktop\dingdong\pick-ticket-damai-main\pick-ticket-damai-main\run.py", line 3, in <module>
    app = Runner()
  File "C:\Users\anji\Desktop\dingdong\pick-ticket-damai-main\pick-ticket-damai-main\damai\runner.py", line 19, in __init__  
    self.engine = ExecutionEngine(self.configs)
  File "C:\Users\anji\Desktop\dingdong\pick-ticket-damai-main\pick-ticket-damai-main\damai\engine.py", line 15, in __init__  
    self.perform = load_object(self.configs["PERFORM"])()
  File "C:\Users\anji\Desktop\dingdong\pick-ticket-damai-main\pick-ticket-damai-main\damai\utils.py", line 36, in load_object
    mod = import_module(module)
  File "C:\Ralf\Program\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load        
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module   
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\anji\Desktop\dingdong\pick-ticket-damai-main\pick-ticket-damai-main\damai\performer.py", line 10, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

应该是报错了

**Comment by lktlktlkt** [comment]
额，你先把requirements.txt里的模块安装好

**Comment by jiancheng87** [comment]
> 额，你先把requirements.txt里的模块安装好

现在貌似是要填CK，是在default_configs.py下填吗？有没有CK的样式模版？
Traceback (most recent call last):
  File "C:\Users\anji\Desktop\dingdong\pick-ticket-damai-main\pick-ticket-damai-main\run.py", line 3, in <module>
    app = Runner()
  File "C:\Users\anji\Desktop\dingdong\pick-ticket-damai-main\pick-ticket-damai-main\damai\runner.py", line 19, in __init__
    self.engine = ExecutionEngine(self.configs)
  File "C:\Users\anji\Desktop\dingdong\pick-ticket-damai-main\pick-ticket-damai-main\damai\engine.py", line 16, in __init__
    self.perform.update_default_config(self.configs)
  File "C:\Users\anji\Desktop\dingdong\pick-ticket-damai-main\pick-ticket-damai-main\damai\performer.py", line 95, in update_default_config
    raise ValueError(f"{self}需要配置COOKIE")
ValueError: <damai.performer.ApiFetchPerform object at 0x046BF748>需要配置COOKIE
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x052017A8>

**Comment by lktlktlkt** [comment]
是的，这个类要使用cookie，在浏览器中复制登录后cookie项。default_configs.py，config.yaml都能配置。
![image](https://github.com/lktlktlkt/pick-ticket-damai/assets/75473618/034ede16-8971-400c-9392-7487adbf840a)

**Comment by lktlktlkt** [comment]
> 下单网页界面出现您选购的商品信息已过期，请重新查询。脚本显示哎哟喂被挤爆了，请稍后重试。知道这是什么问题吗？

网页出现已过期不影响，你可以试试连续刷新网页出现验证码滑动后重新复制cookie，再运行

**Comment by jiancheng87** [comment]
2023-07-07 10:36:49.777 | INFO     | damai.performer:submit:115 - 生成订单：SUCCESS::调用成功
2023-07-07 10:36:50.017 | INFO     | damai.performer:submit:124 - 创建订单：FAIL_SYS_USER_VALIDATE RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试
2023-07-07 10:36:50.251 | INFO     | damai.performer:submit:115 - 生成订单：SUCCESS::调用成功
2023-07-07 10:36:50.429 | INFO     | damai.performer:submit:124 - 创建订单：FAIL_SYS_USER_VALIDATE RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试
2023-07-07 10:36:52.774 | INFO     | damai.performer:submit:115 - 生成订单：SUCCESS::调用成功
2023-07-07 10:36:52.923 | INFO     | damai.performer:submit:124 - 创建订单：FAIL_SYS_USER_VALIDATE RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试

**Comment by jiancheng87** [comment]
2023-07-07 10:36:49.777 | INFO     | damai.performer:submit:115 - 生成订单：SUCCESS::调用成功
2023-07-07 10:36:50.017 | INFO     | damai.performer:submit:124 - 创建订单：FAIL_SYS_USER_VALIDATE RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试
2023-07-07 10:36:50.251 | INFO     | damai.performer:submit:115 - 生成订单：SUCCESS::调用成功
2023-07-07 10:36:50.429 | INFO     | damai.performer:submit:124 - 创建订单：FAIL_SYS_USER_VALIDATE RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试
2023-07-07 10:36:52.774 | INFO     | damai.performer:submit:115 - 生成订单：SUCCESS::调用成功
2023-07-07 10:36:52.923 | INFO     | damai.performer:submit:124 - 创建订单：FAIL_SYS_USER_VALIDATE RGV587_ERROR::SM::哎哟喂,被挤爆啦,请稍后重试
按照你的方式试了还是不行，是不是bx参数没传或者重复使用？

**Comment by lktlktlkt** [comment]
在damai.test.demo中有一个main函数你可以单独运行那个函数，触发验证码后划掉关闭验证码，刷新网页再复制cookie试试。注意那个端口是9223，改成你浏览器开启的端口
